const express = require('express');
const fs = require('fs');
const path = require('path');
const bcrypt = require('bcryptjs');
const cors = require('cors');
const crypto = require('crypto');

const app = express();
const PORT = process.env.PORT || 3000;
const DB_FILE = path.join(__dirname, 'users.json');

app.use(cors({
  origin: true,
  methods: ['GET', 'POST', 'DELETE', 'OPTIONS'],
  allowedHeaders: ['Content-Type']
}));
app.use(express.json());

function readDB() {
  try {
    if (!fs.existsSync(DB_FILE)) return {};
    const data = JSON.parse(fs.readFileSync(DB_FILE, 'utf8'));
    return data && typeof data === 'object' ? data : {};
  } catch (err) {
    console.error('Database read error:', err.message);
    return {};
  }
}

function writeDB(data) {
  const tmp = `${DB_FILE}.tmp`;
  fs.writeFileSync(tmp, JSON.stringify(data, null, 2));
  fs.renameSync(tmp, DB_FILE);
}

function makeSessionId() {
  return `sess_${crypto.randomBytes(32).toString('hex')}`;
}

function cleanDeviceId(value) {
  const id = String(value || '').trim();

  // Device IDs generated by the HTML should be at least 16 chars.
  // Maximum length prevents oversized input.
  if (id.length < 16 || id.length > 256) return '';
  return id;
}

function normalizeUser(user) {
  if (!user || typeof user !== 'object') return user;

  let changed = false;

  if (!Object.prototype.hasOwnProperty.call(user, 'deviceId')) {
    user.deviceId = '';
    changed = true;
  }

  if (!Object.prototype.hasOwnProperty.call(user, 'deviceBoundAt')) {
    user.deviceBoundAt = null;
    changed = true;
  }

  if (!Object.prototype.hasOwnProperty.call(user, 'activeSession')) {
    user.activeSession = '';
    changed = true;
  }

  if (changed) return user;
  return user;
}

function prepareDB(db) {
  let changed = false;

  for (const username of Object.keys(db)) {
    const before = JSON.stringify(db[username]);
    db[username] = normalizeUser(db[username]);
    if (JSON.stringify(db[username]) !== before) changed = true;
  }

  if (changed) writeDB(db);
  return db;
}

async function seedDefaultUsers() {
  const db = prepareDB(readDB());
  let changed = false;

  const defaults = {
    uk0wme: { password: 'ilobyou', days: 300, role: 'admin' },
    ankit: { password: 'gupta', days: 30, role: 'user' },
    rajj: { password: 'rajj', days: 28, role: 'user' },
    john: { password: 'john7698', days: 28, role: 'user' }
  };

  for (const [username, cfg] of Object.entries(defaults)) {
    if (!db[username]) {
      db[username] = {
        password: await bcrypt.hash(cfg.password, 10),
        expiresAt: Date.now() + cfg.days * 24 * 60 * 60 * 1000,
        activeSession: '',
        deviceId: '',
        deviceBoundAt: null,
        role: cfg.role
      };
      changed = true;
    } else {
      const user = normalizeUser(db[username]);

      if (!user.role) {
        user.role = cfg.role;
        changed = true;
      }

      // Existing accounts with no deviceId become bound on their
      // first successful login after this version is deployed.
      if (!Object.prototype.hasOwnProperty.call(user, 'deviceId')) {
        user.deviceId = '';
        user.deviceBoundAt = null;
        changed = true;
      }
    }
  }

  if (changed) writeDB(db);
}

/*
  IMPORTANT SECURITY NOTE

  /users is intentionally limited to account metadata.
  Password hashes are NOT returned.
*/
app.get('/', (req, res) => {
  res.json({
    status: 'ok',
    service: 'my-json-auth-server',
    deviceBinding: 'one-user-one-device',
    endpoints: [
      '/login',
      '/verify-session',
      '/logout',
      '/register',
      '/users'
    ]
  });
});

app.get('/health', (req, res) => {
  res.json({ status: 'ok' });
});

/*
  Returns account metadata only.
  Password hashes are never exposed.
*/
app.get('/users', (req, res) => {
  res.set('Cache-Control', 'no-store');

  const db = prepareDB(readDB());
  const safeUsers = {};

  for (const [username, user] of Object.entries(db)) {
    safeUsers[username] = {
      expiresAt: user.expiresAt,
      activeSession: Boolean(user.activeSession),
      deviceBound: Boolean(user.deviceId),
      deviceBoundAt: user.deviceBoundAt || null,
      role: user.role || 'user'
    };
  }

  res.json(safeUsers);
});

app.post('/register', async (req, res) => {
  try {
    const { username, password, duration, unit } = req.body || {};

    const cleanUsername = String(username || '').trim();
    const cleanPassword = String(password || '');

    if (!cleanUsername || !cleanPassword) {
      return res.status(400).json({
        error: 'Username and password are required'
      });
    }

    if (cleanUsername.toLowerCase() === 'uk0wme') {
      return res.status(409).json({
        error: 'Username already exists'
      });
    }

    const db = prepareDB(readDB());

    if (db[cleanUsername]) {
      return res.status(409).json({
        error: 'Username already exists'
      });
    }

    const dur = Number(duration);

    let ms = 24 * 60 * 60 * 1000;

    if (Number.isFinite(dur) && dur > 0) {
      if (unit === 'minutes') {
        ms = dur * 60 * 1000;
      } else if (unit === 'hours') {
        ms = dur * 60 * 60 * 1000;
      } else {
        ms = dur * 24 * 60 * 60 * 1000;
      }
    }

    db[cleanUsername] = {
      password: await bcrypt.hash(cleanPassword, 10),
      expiresAt: Date.now() + ms,
      activeSession: '',
      deviceId: '',
      deviceBoundAt: null,
      role: 'user'
    };

    writeDB(db);

    res.status(201).json({
      message: 'User created successfully',
      deviceBinding: 'First successful login permanently binds this account to that device.'
    });
  } catch (err) {
    console.error('Register error:', err);
    res.status(500).json({
      error: 'Internal server error'
    });
  }
});

app.delete('/users/:username', (req, res) => {
  const username = decodeURIComponent(req.params.username);

  if (username.toLowerCase() === 'uk0wme') {
    return res.status(400).json({
      error: 'Admin account cannot be deleted'
    });
  }

  const db = prepareDB(readDB());

  if (!db[username]) {
    return res.status(404).json({
      error: 'User not found'
    });
  }

  delete db[username];
  writeDB(db);

  res.json({
    message: 'User deleted successfully'
  });
});

/*
  LOGIN

  First successful login:
    account.deviceId = supplied deviceId

  Future logins:
    supplied deviceId MUST match account.deviceId

  Therefore:
    ONE ACCOUNT -> ONE DEVICE

  Logout does NOT clear deviceId.
*/
app.post('/login', async (req, res) => {
  try {
    const username = String(req.body?.username || '').trim();
    const password = String(req.body?.password || '');
    const deviceId = cleanDeviceId(req.body?.deviceId);

    if (!deviceId) {
      return res.status(400).json({
        error: 'Device ID is required. Refresh the app and try again.',
        code: 'DEVICE_ID_REQUIRED'
      });
    }

    const db = prepareDB(readDB());
    const user = db[username];

    if (!user) {
      return res.status(400).json({
        error: 'Invalid username or password'
      });
    }

    const valid = user.password && user.password.startsWith('$2')
      ? await bcrypt.compare(password, user.password)
      : password === user.password;

    if (!valid) {
      return res.status(400).json({
        error: 'Invalid username or password'
      });
    }

    if (Number(user.expiresAt) <= Date.now()) {
      return res.status(400).json({
        error: 'This account has expired. Contact administrator.',
        code: 'ACCOUNT_EXPIRED',
        expiresAt: user.expiresAt
      });
    }

    /*
      PERMANENT DEVICE BINDING
    */
    if (user.deviceId && user.deviceId !== deviceId) {
      return res.status(403).json({
        error: 'This account is already activated on another device.',
        code: 'DEVICE_BOUND',
        deviceBound: true
      });
    }

    /*
      FIRST LOGIN CLAIMS THE ACCOUNT
    */
    if (!user.deviceId) {
      user.deviceId = deviceId;
      user.deviceBoundAt = Date.now();
    }

    /*
      One active session per account.
      Logging in again on the SAME bound device replaces the
      old session, which causes the previous browser session
      to be logged out.
    */
    const sessionId = makeSessionId();

    user.activeSession = sessionId;

    writeDB(db);

    res.json({
      message: 'Login successful',
      sessionId,
      expiresAt: user.expiresAt,
      deviceBound: true,
      deviceBoundAt: user.deviceBoundAt
    });
  } catch (err) {
    console.error('Login error:', err);

    res.status(500).json({
      error: 'Internal server error'
    });
  }
});

/*
  VERIFY SESSION + DEVICE

  Both must match:
    1. activeSession
    2. deviceId

  This prevents a different device from using a copied session ID.
*/
app.post('/verify-session', (req, res) => {
  const username = String(req.body?.username || '').trim();
  const sessionId = String(req.body?.sessionId || '');
  const deviceId = cleanDeviceId(req.body?.deviceId);

  const db = prepareDB(readDB());
  const user = db[username];

  if (!user || !sessionId || user.activeSession !== sessionId) {
    return res.status(401).json({
      error: 'Session is no longer active.',
      code: 'SESSION_INVALID'
    });
  }

  if (!deviceId || !user.deviceId || user.deviceId !== deviceId) {
    return res.status(403).json({
      error: 'This account is permanently bound to another device.',
      code: 'DEVICE_BOUND'
    });
  }

  if (Number(user.expiresAt) <= Date.now()) {
    return res.status(401).json({
      error: 'Access expired.',
      code: 'ACCOUNT_EXPIRED',
      expiresAt: user.expiresAt
    });
  }

  res.json({
    status: 'active',
    deviceBound: true,
    expiresAt: user.expiresAt,
    deviceBoundAt: user.deviceBoundAt
  });
});

/*
  LOGOUT

  Clears only the session.
  NEVER clears deviceId.

  This means another device cannot claim the account after logout.
*/
app.post('/logout', (req, res) => {
  const username = String(req.body?.username || '').trim();
  const sessionId = String(req.body?.sessionId || '');

  const db = prepareDB(readDB());
  const user = db[username];

  if (user && user.activeSession === sessionId) {
    user.activeSession = '';
    writeDB(db);
  }

  res.json({
    message: 'Logged out. Device binding remains active.',
    deviceBound: Boolean(user?.deviceId)
  });
});

seedDefaultUsers()
  .catch(err => console.error('Seed error:', err));

app.listen(PORT, () => {
  console.log(`Auth server running on port ${PORT}`);
});
